<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void
    {
        Schema::create('accounts', function (Blueprint $table) { $table->id(); $table->foreignId('owner_user_id')->nullable()->constrained('users')->nullOnDelete(); $table->string('name'); $table->decimal('balance',15,2)->default(0.0); $table->string('hash')->nullable(); $table->timestamps(); $table->index('owner_user_id'); });
        Schema::create('customers', function (Blueprint $table) { $table->id(); $table->foreignId('account_id')->constrained('accounts')->onDelete('cascade'); $table->unsignedBigInteger('local_id')->default(0); $table->string('name'); $table->string('phone',50)->nullable(); $table->string('hash')->nullable(); $table->timestamps(); $table->unsignedBigInteger('timestamp')->nullable(); $table->softDeletes(); $table->unique(['account_id','local_id']); });
        Schema::create('suppliers', function (Blueprint $table) { $table->id(); $table->foreignId('account_id')->constrained('accounts')->onDelete('cascade'); $table->unsignedBigInteger('local_id')->default(0); $table->string('name'); $table->string('phone',50)->nullable(); $table->string('hash')->nullable(); $table->timestamps(); $table->unsignedBigInteger('timestamp')->nullable(); $table->softDeletes(); $table->unique(['account_id','local_id']); });
        Schema::create('transactions', function (Blueprint $table) { $table->id(); $table->foreignId('account_id')->constrained('accounts')->onDelete('cascade'); $table->unsignedBigInteger('local_id')->default(0); $table->unsignedBigInteger('customer_id')->nullable(); $table->unsignedBigInteger('supplier_id')->nullable(); $table->string('type',20); $table->decimal('amount',15,2); $table->decimal('amount_sar',15,2)->default(0.00); $table->decimal('customer_rate',10,4)->default(0.0000); $table->decimal('supplier_rate',10,4)->default(0.0000); $table->decimal('amount_bdt',15,2)->default(0.00); $table->string('receiver_name')->nullable(); $table->string('receiver_phone',50)->nullable(); $table->string('receiver_account_type',50)->nullable(); $table->string('receiver_account_no',100)->nullable(); $table->unsignedBigInteger('wallet_batch_id')->nullable(); $table->text('notes')->nullable(); $table->timestamps(); $table->unsignedBigInteger('timestamp')->nullable(); $table->string('hash')->nullable(); $table->softDeletes(); $table->unique(['account_id','local_id']); $table->index('customer_id'); $table->index('supplier_id'); $table->index('wallet_batch_id'); $table->index('timestamp'); });
        Schema::create('rates', function (Blueprint $table) { $table->id(); $table->foreignId('account_id')->constrained('accounts')->onDelete('cascade'); $table->string('currency_pair',10); $table->decimal('rate',15,4); $table->timestamps(); });
        Schema::create('safa_api_keys', function (Blueprint $table) { $table->id(); $table->foreignId('account_id')->nullable()->constrained('accounts')->onDelete('set null'); $table->string('client_name'); $table->string('api_key',128)->unique(); $table->text('api_secret'); $table->boolean('is_active')->default(true); $table->timestamps(); });
        Schema::create('audit_logs', function (Blueprint $table) { $table->id(); $table->unsignedBigInteger('user_id')->nullable()->index(); $table->string('action',10); $table->string('endpoint',255); $table->json('payload')->nullable(); $table->string('ip_address',45)->nullable(); $table->timestamps(); });
        Schema::create('app_versions', function (Blueprint $table) { $table->id(); $table->string('platform',20)->default('android'); $table->integer('min_version_code'); $table->integer('latest_version_code'); $table->boolean('force_update')->default(false); $table->string('update_url')->nullable(); $table->timestamps(); });
        Schema::create('roles', function (Blueprint $table) { $table->id(); $table->string('name',50)->unique(); $table->string('slug',50)->unique(); $table->string('description')->nullable(); $table->timestamps(); });
        Schema::create('permissions', function (Blueprint $table) { $table->id(); $table->string('name',50)->unique(); $table->string('slug',50)->unique(); $table->timestamps(); });
        Schema::create('role_permission', function (Blueprint $table) { $table->foreignId('role_id')->constrained('roles')->onDelete('cascade'); $table->foreignId('permission_id')->constrained('permissions')->onDelete('cascade'); $table->primary(['role_id','permission_id']); });
        Schema::create('wallet_ledgers', function (Blueprint $table) { $table->id(); $table->foreignId('account_id')->constrained('accounts')->onDelete('cascade'); $table->unsignedBigInteger('local_id')->default(0); $table->string('name'); $table->unsignedBigInteger('timestamp')->nullable(); $table->timestamps(); $table->softDeletes(); $table->unique(['account_id','local_id']); });
        Schema::create('wallet_batches', function (Blueprint $table) { $table->id(); $table->foreignId('account_id')->constrained('accounts')->onDelete('cascade'); $table->unsignedBigInteger('local_id')->default(0); $table->unsignedBigInteger('ledger_id')->nullable(); $table->decimal('rate',10,4); $table->decimal('initial_bdt',15,2); $table->decimal('remaining_bdt',15,2); $table->unsignedBigInteger('supplier_id')->nullable(); $table->unsignedBigInteger('supplier_deposit_id')->nullable(); $table->text('notes')->nullable(); $table->unsignedBigInteger('timestamp')->nullable(); $table->timestamps(); $table->softDeletes(); $table->unique(['account_id','local_id']); $table->index('ledger_id'); $table->index('supplier_id'); $table->index('supplier_deposit_id'); $table->index('timestamp'); });
        Schema::create('supplier_deposits', function (Blueprint $table) { $table->id(); $table->foreignId('account_id')->constrained('accounts')->onDelete('cascade'); $table->unsignedBigInteger('local_id')->default(0); $table->unsignedBigInteger('supplier_id')->nullable(); $table->decimal('amount_sar',15,2); $table->decimal('rate',10,4); $table->decimal('amount_bdt',15,2); $table->decimal('paid_bdt',15,2)->default(0.00); $table->string('transaction_type',50)->default('SAR_GIVEN'); $table->text('notes')->nullable(); $table->unsignedBigInteger('timestamp')->nullable(); $table->timestamps(); $table->softDeletes(); $table->unique(['account_id','local_id']); $table->index('supplier_id'); $table->index('timestamp'); });
        Schema::create('expenses_incomes', function (Blueprint $table) { $table->id(); $table->foreignId('account_id')->constrained('accounts')->onDelete('cascade'); $table->unsignedBigInteger('local_id')->default(0); $table->string('title'); $table->decimal('amount',15,2); $table->string('currency',10)->default('BDT'); $table->boolean('is_expense')->default(true); $table->string('category',50)->default('General'); $table->unsignedBigInteger('timestamp')->nullable(); $table->timestamps(); $table->softDeletes(); $table->unique(['account_id','local_id']); });
    }

    public function down(): void { Schema::dropIfExists('expenses_incomes'); Schema::dropIfExists('supplier_deposits'); Schema::dropIfExists('wallet_batches'); Schema::dropIfExists('wallet_ledgers'); Schema::dropIfExists('role_permission'); Schema::dropIfExists('permissions'); Schema::dropIfExists('roles'); Schema::dropIfExists('app_versions'); Schema::dropIfExists('audit_logs'); Schema::dropIfExists('safa_api_keys'); Schema::dropIfExists('rates'); Schema::dropIfExists('transactions'); Schema::dropIfExists('suppliers'); Schema::dropIfExists('customers'); Schema::dropIfExists('accounts'); }
};
